name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image_picker: ^0.8.4+2
  path_provider: ^2.0.1
  http: ^0.13.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  gallery_saver_plus:
    path: ../

flutter:
  uses-material-design: true
